-- rails db < db/country.sql

INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AF', 'Afghanistan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AX', 'Åland Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AL', 'Albania', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('DZ', 'Algeria', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AS', 'American Samoa', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AD', 'Andorra', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AO', 'Angola', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AI', 'Anguilla', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AQ', 'Antarctica', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AG', 'Antigua & Barbuda', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AR', 'Argentina', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AM', 'Armenia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AW', 'Aruba', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AU', 'Australia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AT', 'Austria', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AZ', 'Azerbaijan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BS', 'Bahamas', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BH', 'Bahrain', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BD', 'Bangladesh', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BB', 'Barbados', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BY', 'Belarus', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BE', 'Belgium', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BZ', 'Belize', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BJ', 'Benin', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BM', 'Bermuda', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BT', 'Bhutan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BO', 'Bolivia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BA', 'Bosnia & Herzegovina', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BW', 'Botswana', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BV', 'Bouvet Island', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BR', 'Brazil', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('IO', 'British Indian Ocean Territory', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('VG', 'British Virgin Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BN', 'Brunei', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BG', 'Bulgaria', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BF', 'Burkina Faso', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BI', 'Burundi', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KH', 'Cambodia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CM', 'Cameroon', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CA', 'Canada', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CV', 'Cape Verde', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BQ', 'Caribbean Netherlands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KY', 'Cayman Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CF', 'Central African Republic', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TD', 'Chad', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CL', 'Chile', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CN', 'China', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CX', 'Christmas Island', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CC', 'Cocos (Keeling) Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CO', 'Colombia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KM', 'Comoros', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CG', 'Congo - Brazzaville', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CD', 'Congo - Kinshasa', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CK', 'Cook Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CR', 'Costa Rica', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CI', 'Côte d’Ivoire', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('HR', 'Croatia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CU', 'Cuba', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CW', 'Curaçao', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CY', 'Cyprus', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CZ', 'Czechia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('DK', 'Denmark', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('DJ', 'Djibouti', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('DM', 'Dominica', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('DO', 'Dominican Republic', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('EC', 'Ecuador', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('EG', 'Egypt', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SV', 'El Salvador', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GQ', 'Equatorial Guinea', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('ER', 'Eritrea', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('EE', 'Estonia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SZ', 'Eswatini', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('ET', 'Ethiopia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('FK', 'Falkland Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('FO', 'Faroe Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('FJ', 'Fiji', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('FI', 'Finland', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('FR', 'France', true, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GF', 'French Guiana', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PF', 'French Polynesia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TF', 'French Southern Territories', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GA', 'Gabon', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GM', 'Gambia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GE', 'Georgia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('DE', 'Germany', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GH', 'Ghana', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GI', 'Gibraltar', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GR', 'Greece', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GL', 'Greenland', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GD', 'Grenada', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GP', 'Guadeloupe', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GU', 'Guam', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GT', 'Guatemala', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GG', 'Guernsey', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GN', 'Guinea', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GW', 'Guinea-Bissau', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GY', 'Guyana', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('HT', 'Haiti', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('HM', 'Heard & McDonald Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('HN', 'Honduras', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('HK', 'Hong Kong SAR China', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('HU', 'Hungary', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('IS', 'Iceland', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('IN', 'India', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('ID', 'Indonesia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('IR', 'Iran', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('IQ', 'Iraq', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('IE', 'Ireland', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('IM', 'Isle of Man', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('IL', 'Israel', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('IT', 'Italy', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('JM', 'Jamaica', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('JP', 'Japan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('JE', 'Jersey', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('JO', 'Jordan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KZ', 'Kazakhstan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KE', 'Kenya', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KI', 'Kiribati', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KW', 'Kuwait', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KG', 'Kyrgyzstan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LA', 'Laos', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LV', 'Latvia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LB', 'Lebanon', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LS', 'Lesotho', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LR', 'Liberia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LY', 'Libya', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LI', 'Liechtenstein', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LT', 'Lithuania', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LU', 'Luxembourg', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MO', 'Macao SAR China', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MG', 'Madagascar', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MW', 'Malawi', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MY', 'Malaysia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MV', 'Maldives', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('ML', 'Mali', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MT', 'Malta', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MH', 'Marshall Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MQ', 'Martinique', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MR', 'Mauritania', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MU', 'Mauritius', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('YT', 'Mayotte', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MX', 'Mexico', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('FM', 'Micronesia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MD', 'Moldova', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MC', 'Monaco', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MN', 'Mongolia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('ME', 'Montenegro', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MS', 'Montserrat', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MA', 'Morocco', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MZ', 'Mozambique', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MM', 'Myanmar (Burma)', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NA', 'Namibia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NR', 'Nauru', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NP', 'Nepal', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NL', 'Netherlands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NC', 'New Caledonia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NZ', 'New Zealand', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NI', 'Nicaragua', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NE', 'Niger', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NG', 'Nigeria', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NU', 'Niue', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NF', 'Norfolk Island', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KP', 'North Korea', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MK', 'North Macedonia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MP', 'Northern Mariana Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('NO', 'Norway', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('OM', 'Oman', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PK', 'Pakistan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PW', 'Palau', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PS', 'Palestinian Territories', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PA', 'Panama', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PG', 'Papua New Guinea', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PY', 'Paraguay', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PE', 'Peru', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PH', 'Philippines', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PN', 'Pitcairn Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PL', 'Poland', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PT', 'Portugal', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PR', 'Puerto Rico', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('QA', 'Qatar', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('RE', 'Réunion', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('RO', 'Romania', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('RU', 'Russia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('RW', 'Rwanda', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('WS', 'Samoa', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SM', 'San Marino', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('ST', 'São Tomé & Príncipe', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SA', 'Saudi Arabia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SN', 'Senegal', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('RS', 'Serbia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SC', 'Seychelles', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SL', 'Sierra Leone', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SG', 'Singapore', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SX', 'Sint Maarten', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SK', 'Slovakia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SI', 'Slovenia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SB', 'Solomon Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SO', 'Somalia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('ZA', 'South Africa', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GS', 'South Georgia & South Sandwich Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KR', 'South Korea', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SS', 'South Sudan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('ES', 'Spain', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LK', 'Sri Lanka', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('BL', 'St. Barthélemy', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SH', 'St. Helena', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('KN', 'St. Kitts & Nevis', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('LC', 'St. Lucia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('MF', 'St. Martin', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('PM', 'St. Pierre & Miquelon', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('VC', 'St. Vincent & Grenadines', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SD', 'Sudan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SR', 'Suriname', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SJ', 'Svalbard & Jan Mayen', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SE', 'Sweden', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('CH', 'Switzerland', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('SY', 'Syria', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TW', 'Taiwan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TJ', 'Tajikistan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TZ', 'Tanzania', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TH', 'Thailand', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TL', 'Timor-Leste', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TG', 'Togo', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TK', 'Tokelau', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TO', 'Tonga', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TT', 'Trinidad & Tobago', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TN', 'Tunisia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TR', 'Turkey', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TM', 'Turkmenistan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TC', 'Turks & Caicos Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('TV', 'Tuvalu', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('UM', 'U.S. Outlying Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('VI', 'U.S. Virgin Islands', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('UG', 'Uganda', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('UA', 'Ukraine', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('AE', 'United Arab Emirates', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('GB', 'United Kingdom', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('US', 'United States', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('UY', 'Uruguay', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('UZ', 'Uzbekistan', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('VU', 'Vanuatu', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('VA', 'Vatican City', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('VE', 'Venezuela', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('VN', 'Vietnam', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('WF', 'Wallis & Futuna', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('EH', 'Western Sahara', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('YE', 'Yemen', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('ZM', 'Zambia', false, current_timestamp, current_timestamp);
INSERT INTO countries (acronym, name, active, created_at, updated_at) VALUES ('ZW', 'Zimbabwe', false, current_timestamp, current_timestamp);